import { db } from '@/db';
import { projects } from '@/db/schema';

async function main() {
    const sampleProjects = [
        // User ID "1" - Chioma Adebayo (Product Designer at Flutterwave)
        {
            userId: '1',
            name: 'Flutterwave Mobile App Redesign',
            role: 'Lead Product Designer',
            description: 'Led the complete redesign of Flutterwave\'s mobile banking application, focusing on improving user experience for cross-border payments. Conducted user research across 5 African markets and implemented a new design system that reduced transaction completion time by 40%.',
            category: 'Design',
            link: 'https://www.behance.net/gallery/flutterwave-mobile-redesign',
            status: 'active',
            createdAt: new Date('2023-08-15').getTime(),
            updatedAt: new Date('2024-11-20').getTime(),
        },
        {
            userId: '1',
            name: 'African Design System Library',
            role: 'Design Systems Lead',
            description: 'Created an open-source design system tailored for African fintech products, featuring culturally relevant components, accessibility standards, and multi-currency support. The system is now used by 15+ African startups.',
            category: 'Design',
            link: 'https://github.com/african-design-system',
            status: 'active',
            createdAt: new Date('2023-10-05').getTime(),
            updatedAt: new Date('2024-12-01').getTime(),
        },
        {
            userId: '1',
            name: 'Fintech UX Research Initiative',
            role: 'UX Researcher',
            description: 'Conducted extensive UX research across Nigeria, Kenya, and Ghana to understand payment behaviors and pain points. Published comprehensive research findings that informed product strategy for multiple fintech companies.',
            category: 'Tech',
            link: null,
            status: 'active',
            createdAt: new Date('2023-06-20').getTime(),
            updatedAt: new Date('2024-11-15').getTime(),
        },
        {
            userId: '1',
            name: 'Payment Flow Optimization Project',
            role: 'Senior Product Designer',
            description: 'Redesigned the checkout and payment flows for Flutterwave\'s e-commerce integration, resulting in a 25% increase in successful transactions and improved user satisfaction scores.',
            category: 'Design',
            link: 'https://www.figma.com/community/payment-flow-optimization',
            status: 'active',
            createdAt: new Date('2024-02-10').getTime(),
            updatedAt: new Date('2024-12-05').getTime(),
        },

        // User ID "2" - Kwame Osei (Software Engineering Lead at Andela)
        {
            userId: '2',
            name: 'Distributed Learning Platform',
            role: 'Technical Lead',
            description: 'Architected and built a scalable distributed learning management system using React, Python Django, and AWS. The platform serves 50,000+ students across Africa with real-time collaboration features and video streaming capabilities.',
            category: 'Tech',
            link: 'https://github.com/kwame-osei/distributed-learning-platform',
            status: 'active',
            createdAt: new Date('2023-05-12').getTime(),
            updatedAt: new Date('2024-11-28').getTime(),
        },
        {
            userId: '2',
            name: 'Open Source CI/CD Pipeline Tool',
            role: 'Core Maintainer',
            description: 'Created and maintain an open-source CI/CD automation tool built with Python that simplifies deployment workflows for microservices. The project has 3,500+ GitHub stars and is used by companies worldwide.',
            category: 'Tech',
            link: 'https://github.com/kwame-osei/cicd-automation-tool',
            status: 'active',
            createdAt: new Date('2023-09-08').getTime(),
            updatedAt: new Date('2024-12-03').getTime(),
        },
        {
            userId: '2',
            name: 'Cloud Migration Framework for African SMEs',
            role: 'Solutions Architect',
            description: 'Developed a comprehensive framework and toolkit to help small and medium enterprises migrate legacy systems to cloud infrastructure with minimal downtime. Successfully migrated 20+ companies to AWS and Google Cloud.',
            category: 'Tech',
            link: null,
            status: 'active',
            createdAt: new Date('2024-01-15').getTime(),
            updatedAt: new Date('2024-11-25').getTime(),
        },
        {
            userId: '2',
            name: 'Real-time Data Processing Engine',
            role: 'Engineering Lead',
            description: 'Built a high-performance real-time data processing engine using Python and Apache Kafka that handles 1M+ events per second. The system powers analytics dashboards for multiple Andela client projects.',
            category: 'Startups',
            link: 'https://github.com/andela/realtime-data-engine',
            status: 'active',
            createdAt: new Date('2023-11-20').getTime(),
            updatedAt: new Date('2024-12-08').getTime(),
        },
        {
            userId: '2',
            name: 'Andela Developer Portal',
            role: 'Lead Developer',
            description: 'Created a comprehensive developer portal for Andela engineers featuring project management tools, code review workflows, and knowledge sharing features. The portal improved team collaboration efficiency by 35%.',
            category: 'Tech',
            link: 'https://developers.andela.com',
            status: 'active',
            createdAt: new Date('2024-03-05').getTime(),
            updatedAt: new Date('2024-11-30').getTime(),
        },

        // User ID "3" - Amina Mohammed (Data Scientist at Jumia)
        {
            userId: '3',
            name: 'E-commerce Recommendation Engine',
            role: 'Lead Data Scientist',
            description: 'Designed and deployed a machine learning recommendation system using collaborative filtering and deep learning that increased product discovery by 45% and boosted cross-selling revenue by 30% across Jumia\'s platform.',
            category: 'Tech',
            link: null,
            status: 'active',
            createdAt: new Date('2023-07-18').getTime(),
            updatedAt: new Date('2024-12-02').getTime(),
        },
        {
            userId: '3',
            name: 'Customer Analytics Dashboard',
            role: 'Senior Data Scientist',
            description: 'Built an interactive analytics dashboard using Python, Tableau, and BigQuery that provides real-time insights into customer behavior, purchase patterns, and lifetime value metrics. Used by 50+ business stakeholders daily.',
            category: 'Tech',
            link: 'https://github.com/amina-mohammed/customer-analytics-dashboard',
            status: 'active',
            createdAt: new Date('2023-09-25').getTime(),
            updatedAt: new Date('2024-11-22').getTime(),
        },
        {
            userId: '3',
            name: 'ML Model for Fraud Detection',
            role: 'Machine Learning Engineer',
            description: 'Developed an advanced fraud detection system using ensemble learning and neural networks that reduced fraudulent transactions by 60%. The model processes 100,000+ transactions daily with 99.2% accuracy.',
            category: 'Tech',
            link: null,
            status: 'active',
            createdAt: new Date('2024-01-08').getTime(),
            updatedAt: new Date('2024-12-06').getTime(),
        },
        {
            userId: '3',
            name: 'Data Science Mentorship Program',
            role: 'Program Lead & Instructor',
            description: 'Founded and lead a mentorship program that has trained 200+ aspiring data scientists across Africa. Created comprehensive curriculum covering Python, ML, and data engineering with hands-on projects.',
            category: 'Education',
            link: 'https://datascience-mentorship-africa.com',
            status: 'active',
            createdAt: new Date('2023-04-12').getTime(),
            updatedAt: new Date('2024-11-18').getTime(),
        },

        // User ID "4" - Thabo Nkosi (Founder & CEO at GreenTech Solutions)
        {
            userId: '4',
            name: 'Solar Power Management System',
            role: 'Founder & Product Lead',
            description: 'Built an IoT-enabled solar power management platform that optimizes energy distribution for homes and businesses across South Africa. The system has helped 500+ customers reduce energy costs by 50% while promoting renewable energy adoption.',
            category: 'Startups',
            link: 'https://greentech-solutions.co.za/solar-management',
            status: 'active',
            createdAt: new Date('2023-03-22').getTime(),
            updatedAt: new Date('2024-11-27').getTime(),
        },
        {
            userId: '4',
            name: 'Carbon Footprint Tracker App',
            role: 'CEO & Co-Creator',
            description: 'Launched a mobile application that helps individuals and companies track and reduce their carbon footprint through AI-powered recommendations. The app has 25,000+ active users and partnerships with 15 corporations.',
            category: 'Tech',
            link: 'https://apps.apple.com/carbon-tracker-africa',
            status: 'active',
            createdAt: new Date('2023-08-30').getTime(),
            updatedAt: new Date('2024-12-04').getTime(),
        },
        {
            userId: '4',
            name: 'Green Energy Marketplace',
            role: 'Founder',
            description: 'Created Africa\'s first marketplace connecting renewable energy providers with consumers and businesses. The platform facilitates transparent pricing, easy switching between providers, and has enabled $5M+ in green energy transactions.',
            category: 'Startups',
            link: 'https://green-energy-marketplace.com',
            status: 'active',
            createdAt: new Date('2024-02-14').getTime(),
            updatedAt: new Date('2024-11-19').getTime(),
        },
        {
            userId: '4',
            name: 'Climate Tech Accelerator Program',
            role: 'Program Director',
            description: 'Co-founded an accelerator program focused on nurturing climate tech startups in Africa. Successfully supported 30+ startups with funding, mentorship, and resources. Portfolio companies have raised $12M+ in total funding.',
            category: 'Startups',
            link: null,
            status: 'active',
            createdAt: new Date('2023-06-05').getTime(),
            updatedAt: new Date('2024-12-01').getTime(),
        },

        // User ID "5" - Fatima Diallo (Marketing Director at Wave Mobile Money)
        {
            userId: '5',
            name: 'Wave Regional Expansion Campaign',
            role: 'Campaign Director',
            description: 'Led multi-channel marketing campaigns for Wave\'s expansion into 3 new African markets, resulting in 500,000+ new user acquisitions in 6 months. The campaign included localized content, influencer partnerships, and community engagement initiatives.',
            category: 'Marketing',
            link: null,
            status: 'active',
            createdAt: new Date('2023-10-10').getTime(),
            updatedAt: new Date('2024-11-29').getTime(),
        },
        {
            userId: '5',
            name: 'Fintech Content Marketing Hub',
            role: 'Content Strategy Lead',
            description: 'Developed and launched a comprehensive content marketing platform featuring financial literacy resources, video tutorials, and community stories. The hub attracts 100,000+ monthly visitors and improved brand awareness by 60%.',
            category: 'Finance',
            link: 'https://wave.com/learn',
            status: 'active',
            createdAt: new Date('2024-01-20').getTime(),
            updatedAt: new Date('2024-12-07').getTime(),
        },
        {
            userId: '5',
            name: 'User Acquisition Analytics Framework',
            role: 'Growth Marketing Director',
            description: 'Built a data-driven framework for tracking and optimizing user acquisition across digital channels. Implemented attribution modeling and cohort analysis that reduced customer acquisition cost by 35% while improving conversion rates.',
            category: 'Marketing',
            link: 'https://github.com/fatima-diallo/growth-analytics-framework',
            status: 'active',
            createdAt: new Date('2023-07-28').getTime(),
            updatedAt: new Date('2024-11-24').getTime(),
        },
        {
            userId: '5',
            name: 'Financial Inclusion Campaign',
            role: 'Marketing Director',
            description: 'Spearheaded a social impact campaign promoting financial inclusion for underserved communities across West Africa. The campaign reached 2M+ people and resulted in 150,000 new mobile money accounts opened by first-time digital banking users.',
            category: 'Finance',
            link: 'https://wave.com/financial-inclusion',
            status: 'active',
            createdAt: new Date('2023-05-16').getTime(),
            updatedAt: new Date('2024-12-05').getTime(),
        },
    ];

    await db.insert(projects).values(sampleProjects);
    
    console.log('✅ Projects seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});